# Generated by Django 5.0.4 on 2024-05-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_imageproduct_productinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='image',
        ),
    ]
