# Generated by Django 5.0.4 on 2024-05-01 17:57

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_productinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products_images/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='ImageProduct',
        ),
    ]
